#!/usr/bin/env bash
# Script that executes a sequence of the following commands
sudo apt-get -y update # Updates the default packages installed
sudo apt-get -y install nginx # Installs nginx package
echo "Hello World" > /var/www/html/index.html # Creates an html file with "Hello World" inside the /var path 
service nginx start # Runs nginx
