#!/usr/bin/env bash
# This script will print a Message indefinitely
# And every time recives a signal will print another msg
# It will wait 2 seconds on every iteration

trap "echo 'I am invincible!!!'" SIGTERM
while true ; do
    echo "To infinity and beyond"
    sleep 2
done