#!/usr/bin/env bash
# This script will check the number 'i' and display text in certain cases
# Using the 'while' loop and the 'case" statement

i=0

while [ $i -le 19 ]; do
    i=$((i+1))
    echo $i
    case $i in
        4)  echo "bad luck from China"  ;;
        9)  echo "bad luck from Japan"  ;;
        17) echo "bad luck from Italy"  ;;
    esac
done